### ISSUE TITLE
Agent "exec-status" Error 400 Parameter verification failed.

### ISSUE THREAD

**Issue by a1um1** [UrielCh/proxmox-api#11] opened 2022-08-24 11:56 UTC
I got this error with exec-status
```
GET https://192.168.1.2:8006/api2/json/nodes/pve/qemu/102/agent/exec-status?pid=2688

return Error 400 Parameter verification failed.:

{\"errors\":{\"pid\":\"property is missing and it is not optional\"},\"data\":null}"
```
## Replication problems
create agent exec and retrive pid
and call agent exec-status should replicate an error
but try to access that URL with browser will result like it's seem to be

**Comment by UrielCh** [comment] 2022-09-14 07:46
I think the issue is now fixed, but I would like to test it first.

how did you get the pid ?
is that the PID of a process inside the qemu ?
is the agent able to list the running processes ?

**Comment by a1um1** [comment] 2022-09-14 08:03
1. I retrive PID by using /agent/exec on qemu
2. PID is process inside qemu
3. Agent can retrive running process as normal via command or postman
-
I think it's occured by parsing problem
it's have this same problem with qemu rrddata and /agent/file-read method
or anything that use GET query params

**Comment by UrielCh** [comment] 2022-09-14 08:06
is that work on windows VM qemu?
so it only works on the process starting via the agent?

have you a sample command I can exec in a windows QEMU agent to get its exec-status?

**Comment by a1um1** [comment] 2022-09-14 08:11
```
await agent.ping.$post()
const {pid} = await proxmox.nodes.$(query.node).qemu.$(query.vmID).agent.exec.$post({
command: `powershell.exe ping 127.0.0.1`,
})
const result = await proxmox.nodes.$(query.node).qemu.$(query.vmID).agent['exec-status'].$get({
pid:pid
})
```

**Comment by UrielCh** [comment] 2022-09-14 08:17
The test is in progress, but I need to switch to another project; I'll be back in 30 minutes.

Your "powershell.exe ping 127.0.0.1" look more promising than my "echo hello" :)

**Comment by UrielCh** [comment] 2022-09-14 08:26
I need to fix an offline remote server, which will take more time than expected. I will finish that within 12hours.

**Comment by UrielCh** [comment] 2022-09-14 15:24
I do not have powershell.exe on my remote Windows :(

**Comment by a1um1** [comment] 2022-09-14 16:16
cmd.exe should do a job
what windows version are you on

**Comment by UrielCh** [comment] 2022-09-14 16:56
can you try v 0.4.1

extract from sample.ts:
```typescript
            try {
                const mtd1 = theNode.qemu.$(qemu.vmid).agent.exec.$post;
                // const process = await exec.$post({ command: "powershell.exe ping 127.0.0.1" })
                const process = await mtd1({ command: "C:/Windows/System32/ping.exe 127.0.0.1" })
                console.log('pid:', process.pid)
                const getter = theNode.qemu.$(qemu.vmid).agent["exec-status"].$get;
                let exited = false;
                let waitcnd = 0;
                while (!exited) {
                    const status = await getter({ pid: process.pid })
                    console.log(++waitcnd + ' status:', status)
                    exited = !!status.exited;
                    await delay(500);
                }
                // { exited: 0 }
                // { exitcode: 0, exited: 1, out-data: 'stdout'}
            } catch (e) {
                console.log(e);
            }
```

**Comment by a1um1** [comment] 2022-09-14 17:06
v 0.4.1 is fixed this issues with every GET method
so you can close this issue now
Thank for supporting

**Closed as completed** 2022-09-14 17:09 UTC
